swagger: "2.0"
info:
  title: StyleSnap API
  version: 1.0.0
schemes:
  - http
  - https
paths:
  /auth/signup:
    post:
      tags:
        - User
      summary: Sign up a new user
      parameters:
        - name: body
          in: body
          description: User object
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: User registration successful.
          schema:
            $ref: "#/definitions/BaseResponse"
        422:
          description: Invalid user registration data.
          schema:
            allOf:
              - $ref: "#/definitions/BaseResponse"
              - type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        500:
          description: Internal server error.
          schema:
            $ref: "#/definitions/BaseResponse"
  /auth/login:
    post:
      tags:
        - User
      summary: Login a user
      parameters:
        - name: body
          in: body
          description: User object
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: User login successful.
          schema:
            allOf:
              - $ref: "#/definitions/BaseResponse"
              - type: object
                properties:
                  accessToken:
                    type: string
        422:
          description: Invalid user login data.
          schema:
            $ref: "#/definitions/BaseResponse"
        500:
          description: Internal server error.
          schema:
            $ref: "#/definitions/BaseResponse"
  /auth/authtest:
    post:
      tags:
        - User
      summary: Test authentication
      security:
        - jwt: []
      responses:
        200:
          description: Authentication successful.
          schema:
            $ref: "#/definitions/BaseResponse"
        401:
          description: Authentication failed.
          schema:
            $ref: "#/definitions/BaseResponse"
definitions:
  BaseResponse:
    type: object
    properties:
      message:
        type: string
  User:
    type: object
    properties:
      username:
        type: string
        example: "johndoe"
      password:
        type: string
        example: "password"
      email:
        type: string
        example: "johndoe@email.com"
  
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header